# Generated by Django 4.0.1 on 2022-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedocument',
            name='eighth_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
