# Generated by Django 4.0.1 on 2022-03-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_studentofferletterfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentofferletterfee',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
        ),
    ]
