# Generated by Django 4.0.1 on 2022-03-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_assignment_marks',
            new_name='subject_external_marks',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_exam_marks',
            new_name='subject_internal_marks',
        ),
    ]
