# Generated by Django 4.0.1 on 2022-03-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_studentpaymentreceive'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentreceive',
            name='payment_options',
            field=models.CharField(choices=[(1, 'Cash'), (2, 'Online Payment Gateway'), (3, 'Bank Transfer'), (4, 'others')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='studentpaymentreceive',
            name='payment_status',
            field=models.CharField(choices=[(1, 'fully paid'), (2, 'partial paid'), (3, 'unpaid')], default=1, max_length=10),
        ),
    ]
