# Generated by Django 4.0.1 on 2022-03-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_studentresult_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='semester_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semesters'),
            preserve_default=False,
        ),
    ]
