# Generated by Django 4.0.1 on 2022-03-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_studentresult_semester_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
    ]
