# Generated by Django 4.0.1 on 2022-03-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_studentpaymentreceive_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaymentreceive',
            name='payment_options',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentpaymentreceive',
            name='payment_status',
            field=models.CharField(max_length=255),
        ),
    ]
