# Generated by Django 4.0.1 on 2022-03-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_alter_studentpaymentreceive_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentreceive',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
        ),
    ]
