# Generated by Django 4.0.1 on 2022-03-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_courses_staff_semesters_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
