# Generated by Django 4.0.1 on 2022-04-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_studentpaymentreceive_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentofferletterfee',
            name='currency_type',
            field=models.CharField(default='INR', max_length=255),
        ),
    ]
