# Generated by Django 4.0.1 on 2022-04-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_studentofferletterfee_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentofferletterfee',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=255),
        ),
    ]
