# Generated by Django 4.0.1 on 2022-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_courses_course_code_subjects_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='exam_months',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
