# Generated by Django 4.0.1 on 2022-04-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_studentpaymentreceive_student_id'),
        ('student_management_app', '0011_studentresult_exam_months'),
    ]

    operations = [
    ]
