# Generated by Django 4.0.1 on 2022-04-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_studentofferletterfee_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentofferletterfee',
            name='inr_fees',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
