# Generated by Django 4.0.1 on 2022-04-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_merge_20220402_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='exam_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='semester_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semesters'),
        ),
    ]
