# Generated by Django 4.0.1 on 2022-04-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_studentresult_exam_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
    ]
