# Generated by Django 4.0.1 on 2022-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_alter_studentofferletterfee_inr_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentofferletterfee',
            name='inr_fees',
            field=models.CharField(max_length=255),
        ),
    ]
