# Generated by Django 4.0.1 on 2022-04-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_alter_studentofferletterfee_inr_fees'),
        ('student_management_app', '0014_studentresult_total_marks'),
    ]

    operations = [
    ]
