# Generated by Django 4.0.1 on 2022-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_merge_20220421_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentreceive',
            name='currency_type',
            field=models.CharField(default='INR', max_length=255),
        ),
        migrations.AddField(
            model_name='studentpaymentreceive',
            name='inr_fees',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentpaymentreceive',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
