# Generated by Django 4.0.1 on 2022-04-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_examcourses_students_exam_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='exam_course',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.examcourses'),
        ),
    ]
