# Generated by Django 4.0.1 on 2022-04-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_alter_students_exam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='exam_course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.examcourses'),
        ),
    ]
