# Generated by Django 4.0.1 on 2022-04-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_studentpaymentreceive_currency_type_and_more'),
        ('student_management_app', '0018_studentresult_exam_course_id'),
    ]

    operations = [
    ]
