# Generated by Django 4.0.1 on 2022-04-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0019_merge_20220425_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='exam_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.examcourses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='exam_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.examcourses'),
        ),
    ]
