# Generated by Django 4.0.1 on 2022-04-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_alter_studentresult_exam_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='exam_course_id',
        ),
    ]
