# Generated by Django 4.0.1 on 2022-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0021_remove_studentresult_exam_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
